### PR TITLE
Fixes #46

### LINKED ISSUE #46: Non-pixel font sizes aren't converted correctly
Relates to https://github.com/jpuri/draftjs-to-html/issues/36

Per the CSS spec, `font-size` can take absolute and relative values, as well as global values, e.g:
`font-size: medium;`
`font-size: larger;`
`font-size: inherit;`

This library currently assumes all font sizes are in pixels, and just removes the last two characters.

Steps to reproduce:

1. Go to https://jpuri.github.io/react-draft-wysiwyg/#/demo
2. On the first demo (which shows you the outputted html), copy the text which is there, then paste.

Result:

image

The outputted html has `font-size: medipx`.

I am working on a fix for this and hope to get a PR open shortly.

### PR DESCRIPTION
**Pull request by mjgreen145**
Related issue: https://github.com/jpuri/html-to-draftjs/issues/46

This change explicitly removes the string `px` from a font-size, rather than just the last two characters

### CODE REVIEW

File: src/library/processInlineTag.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default function processInlineTag(
         style.add(`bgcolor-${backgroundColor.replace(/ /g, '')}`);
       }
       if (fontSize) {
-        style.add(`fontsize-${fontSize.substr(0, fontSize.length - 2)}`);
+        style.add(`fontsize-${fontSize.replace(/px$/g, '')}`);
       }
```
Comment (jpuri) [inline src/library/processInlineTag.js]: Change looks good I am just thinking why not trim and then remove last 2 chars.

Comment (mjgreen145) [reply src/library/processInlineTag.js]: I'm not quite sure what you mean by 'trim'. The issue with removing the last two characters is if `fontSize` is `inherit`, or `medium`, in which case you don't want to lose the last two chars.

Comment (jpuri) [reply src/library/processInlineTag.js]: Ah I get you point - I was thinking only about px values, thanks.

**Comment by jpuri** [comment]
Change has been released in `html-to-draftjs@1.2.0`.
